name:                DAGr
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/wbadart/DAGr
license:             GPL3
author:              Will Badart
maintainer:          will@willbadart.com
copyright:           2020 Will Badart
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- jsonpycomp
- language-python
- wai-cors
- warp
- yesod

executables:
  DAGr:
    source-dirs:      src
    main:             Main.hs
